### ISSUE TITLE
"scoped-threadpool" and leaked memory

### ISSUE THREAD

**Issue by maxcountryman** [njaard/scope-threadpool#3]
In this project's README you've linked to an issue you created on the the scoped-threadpool project page, i.e. Kimundi/scoped-threadpool-rs#16.

However the [test case provided](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=e8bb4f64757ad90d4c5247a98b93cfd4) seems to pass on stable and nightly Rust.

Is this still an issue?

**Comment by Boscop** [comment]
Yeah, I'd like to know, too..

**Comment by njaard** [comment]
i don't know, I will remove reference to that problem and close this ticket.
